#! /bin/sh
#
# Update link-library symlinks after a Python default runtime change

set -e

die() {
    echo "$@" >&2
    exit 1
}

update_linklibs() {
    py=$1
    suf=$2

    cd /usr/lib
    for thread in "" -mt; do
	target=libboost_python${thread}${debug}-${py}.${suf}
	link=libboost_python${thread}${debug}.${suf} 
	test -e $target && ln -s -f $target $link
    done
}

remove_linklibs() {
    suf=$1

    cd /usr/lib
    for thread in "" -mt; do
	rm -f libboost_python${thread}${debug}.${suf} 
    done
}

rtupdate() {
    case "$1" in
	python2.4)  py=py24 ;;
	python2.5)  py=py25 ;;
	*)          remove ; return ;;
    esac

    update_linklibs $py a
    update_linklibs $py so
}

remove() {
    remove_linklibs a
    remove_linklibs so
}


debug=
case "$0" in
    */libboost-dbg.rtupdate)  debug=-d ;;
esac

action="$1"
shift

case "$action" in
    pre-rtupdate)  ;;
    post-rtupdate) ;;
    rtupdate)      rtupdate $2 ;;
    remove)        remove ;;
    *)             die "$0 called with unknown argument '$action'" ;;
esac

